### ISSUE TITLE
Bug - File "adafruit_register/i2c_struct_array.py", line 63, in __getitem__

### ISSUE THREAD

**Issue by renannn** [adafruit/Adafruit_CircuitPython_Register#51]
I was developing a device using this framework, but it started showing the following error and I don't know how to proceed.

Traceback (most recent call last):
  File "code.py", line 140, in <module>
  File "adafruit_mpu6050.py", line 270, in acceleration
  File "adafruit_register/i2c_struct_array.py", line 63, in __getitem__
OSError: [Errno 19] No such device
![Erro](https://github.com/adafruit/Adafruit_CircuitPython_Register/assets/40036259/3005d4b1-7b40-42cb-977b-f64bae785ff2)

Can anyone help me with this ?

**Comment by tannewt** [comment]
Is the device a MPU6050. That would happen if the device stopped responding to I2C communication. Why controller device are you using this with?

**Comment by grgrant** [comment]
@tannewt Can this be closed?  There was no reply to your followup question in 2023.

**Comment by tannewt** [comment]
Yup! Thanks!
